#pragma once
#include "bot.hpp"
#include "luaglue.h"


namespace altplay {
	namespace script {
		extern void initScripts();

    // according to RFC 2812
    enum IRCReply {
      WELCOME = 1, YOURHOST, CREATED, MYINFO, BOUNCE,

      TRACELINK   = 200, TRACECONNECTING, TRACEHANDSHAKE,
      TRACEUNKNOWN, TRACEOPERATOR, TRACEUSER, TRACESERVER,
      TRACESERVICE, TRACENEWTYPE, TRACECLASS, TRACERECONNECT,
      STATSLINKINFO, STATSCOMMANDS,
      ENDOFSTATS  = 219,

      UMODEIS     = 221,

      SERVLIST    = 234, SERVLISTEND,

      STATSUPTIME = 242, STATSONLINE,

      LUSERCLIENT = 251, LUSEROP, LUSERUNKNOWN, LUSERCHANNELS, LUSERME,
      ADMINME, ADMINLOC1, ADMINLOC2, ADMINEMAIL, TRACELOG, TRACEEND, TRYAGAIN,

      AWAY        = 301, USERHOST, ISON, UNAWAY, NOWAWAY,

      WHOISUSER   = 311, WHOISSERVER, WHOISOPERATOR, WHOWASUSER, ENDOFWHO,
      WHOISIDLE   = 317, ENDOFWHOIS, WHOISCHANNELS,

      LISTSTART   = 321 /*OBSOLETE, to be removed*/, LIST, LISTEND, CHANNELMODEIS,
      UNIQOPIS,

      NOTOPIC     = 331, TOPIC,

      INVITING    = 341, SUMMONING, INVITELIST = 346, ENDOFINVITELIST,
      EXCEPTLIST, ENDOFEXCEPTLIST,

      VERSION     = 351, WHOREPLY, NAMREPLY,

      LINKS       = 364, ENDOFLINKS, ENDOFNAMES, BANLIST, ENDOFBANLIST, ENDOFWHOWAS,
      INFO        = 371, MOTD,
      ENDOFINFO   = 374, MOTDSTART, ENDOFMOTD,
      YOUREOPER   = 381, REHASHING, YOURESERVICE,
      IME         = 391, USERSSTART, USERS, ENDOFUSERS, NOUSERS
    };

    // IRC errors
    enum IRCError {
      NOSUCHNICK = 401, NOSUCHSERVER, NOSUCHCHANNEL, CANNOTSENDTOCHAN,
      TOOMANYCHANNELS, WASNOSUCHNICK, TOOMANYTARGETS, NOSUCHSERVICE, NOORIGIN,
      
      NORECIPIENT = 411, NOTEXTTOSEND, NOTOPLEVEL, WILDTOPLEVEL, BADMASK,
      
      UNKNOWNCOMMAND = 421, NOMOTD, NOADMININFO, FILEERROR,
      
      NONICKNAMEGIVEN = 431, ERRONEUSNICKNAME, NICKNAMEINUSE, NICKCOLLISION,
      UNAVAILRESOURCE,
      
      USERNOTINCHANNEL = 441, NOTONCHANNEL, USERONCHANNEL, NOLOGIN,
      SUMMONDISABLED, USERSDISABLED,
      
      NOTREGISTERED = 451, NEEDMOREPARAMS = 461, ALREADYREGISTERED, NOPERMFORHOST,
      PASSWDMISMATCH, YOUREBANNEDCREEP, YOUWILLBEBANNED, KEYSET,
      
      CHANNELISFUL = 471, UNKNOWNMODE, INVITEONLYCHAN, BANNEDFROMCHAN, BADCHANNELKEY,
      BADCHANMASK, NOCHANMODES, BANLISTFULL,
      
      NOPRIVILEGES = 481, CHANOPPRIVSNEEDED, CANTKILLSERVER, RESTRICTED, UNIQOPPRIVSNEEDED,

      NOOPERHOST = 491, UMODEUNKNOWNFLAG = 501, USERSDONTMATCH
    };
	}
}
